### ISSUE TITLE
pakage is not in comoposer

### ISSUE THREAD

**Issue by mohamad68** [akiyamaSM/oxfordapi-wrapper#2]
oxfordapi_wrapper is not in composer pakage list.

 Could not find package inani/oxfordapi-wrapper at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by akiyamaSM** [comment]
Its weird, everything is set.

**Comment by mohamad68** [comment]
thank you for replay . now i download it and i am using it.
