### ISSUE TITLE
oxford response error

### ISSUE THREAD

**Issue by mohamad68** [akiyamaSM/oxfordapi-wrapper#3]
hi
I get error can you help me?
my code :
```
Route::get('test',function (){
    $oxford = app(Inani\OxfordApiWrapper\OxfordWrapper::class);
    $parser =$oxford->lookFor('balablabla')
        ->from('en')
        ->to('es')
        ->translate();
    echo $parser->get();
}); 
```
error : 
```
ClientException in RequestException.php line 111:
Client error: `GET https://od-api.oxforddictionaries.com/api/api/v1/entries/en/balablabla/translations=es` resulted in a `404 NOT FOUND` response:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested (truncated...)
```
instead use ''balablabla' , i use another words like 'nice' , 'hello',.........
but get same error.

**Comment by akiyamaSM** [comment]
in your base configuration make sure its like that
OXFORD_API_BASE_URI = https://od-api.oxforddictionaries.com
without the /api path

**Comment by mohamad68** [comment]
Wow woW . yes the problem was in path . i remove the '/api ' and it's work now. 
thank you again.

**Comment by akiyamaSM** [comment]
You are welcome, if you need something specific to be implemented based on the Oxford dictionary feel free to open a new issue
