### ISSUE TITLE
pronunciations audio of word 

### ISSUE THREAD

**Issue by mohamad68** [akiyamaSM/oxfordapi-wrapper#4]
hi
I wish this wrapper was wrapping pronunciations, audio (British & USA )  and phonetic of oxford dictionary

**Comment by akiyamaSM** [comment]
Sure, Hope I'll be able to make it this weekend.

**Comment by mohamad68** [comment]
I appreciate your attempt,

**Comment by akiyamaSM** [comment]
@mohamad68 its now supported, Actually there is only British :(
